version: '2'
workflows:
  version: '2'
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
jobs:
  - build:
      docker:
        - &ref_0
          image: 'circleci/node:latest'
      steps:
        - checkout
        - restore_cache:
            keys:
              - 'v1-deps-{{ checksum "yarn.lock" }}'
              - v1-deps-
            name: Restoring Cache
        - run: yarn install --frozen-lockfile
        - save_cache:
            paths:
              - ~/project
            key: 'v1-repo-{{ .Revision }}'
            name: Saving Cache
            when: always
        - save_cache:
            paths:
              - ~/project/node_modules
            key: 'v1-deps-{{ checksum "yarn.lock" }}'
            name: Saving Cache
            when: always
  - test:
      docker:
        - *ref_0
      steps:
        - restore_cache:
            key: 'v1-repo-{{ .Revision }}'
            name: Restoring Cache
        - run: yarn jest
  - lint:
      docker:
        - *ref_0
      steps:
        - restore_cache:
            key: 'v1-repo-{{ .Revision }}'
            name: Restoring Cache
        - run: yarn lint
